// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlPQtV0vJKi-_psB5_B2SUk66r4Whk0BE',
    appId: '1:9113993235:web:3bbdf0baabb6cc31653fe6',
    messagingSenderId: '9113993235',
    projectId: 'crudfire-8af74',
    authDomain: 'crudfire-8af74.firebaseapp.com',
    storageBucket: 'crudfire-8af74.appspot.com',
    measurementId: 'G-TCHBQY3VMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUqMtejrQcZhxgTJFVizzGpM1zF-oJO4g',
    appId: '1:9113993235:android:8b8c7c4cfbdd5654653fe6',
    messagingSenderId: '9113993235',
    projectId: 'crudfire-8af74',
    storageBucket: 'crudfire-8af74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnp_KVkvz_wjpRK4GDH45qw-t-nz1BBC8',
    appId: '1:9113993235:ios:54646fa6af1d05a5653fe6',
    messagingSenderId: '9113993235',
    projectId: 'crudfire-8af74',
    storageBucket: 'crudfire-8af74.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnp_KVkvz_wjpRK4GDH45qw-t-nz1BBC8',
    appId: '1:9113993235:ios:54646fa6af1d05a5653fe6',
    messagingSenderId: '9113993235',
    projectId: 'crudfire-8af74',
    storageBucket: 'crudfire-8af74.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlPQtV0vJKi-_psB5_B2SUk66r4Whk0BE',
    appId: '1:9113993235:web:26c72cbf1786355f653fe6',
    messagingSenderId: '9113993235',
    projectId: 'crudfire-8af74',
    authDomain: 'crudfire-8af74.firebaseapp.com',
    storageBucket: 'crudfire-8af74.appspot.com',
    measurementId: 'G-2QQ64N7Z2K',
  );
}
